<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
	<Nullable>enable</Nullable>
	<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	<IsRoslynComponent>true</IsRoslynComponent>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Bcl.Memory" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.9.0" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
  </ItemGroup>

</Project>
