using Microsoft.CodeAnalysis;
using NodeEditor.SourceGenerator.Helpers;
using NodeEditor.SourceGenerator.Models;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace NodeEditor.SourceGenerator.Generators
{
    internal partial class NodeEditors
    {
        private void BuildCustomNodeRegistry(SourceProductionContext context, (ImmutableArray<CustomEditorModel?> Left, string Right) tuple)
        {
            var models = tuple.Left;
            var rootNamespace = tuple.Right;

            var sb = new IndentedStringBuilder();

            sb.AppendLine($"// autogenerated on {DateTime.UtcNow}");
            sb.AppendLine($"namespace {rootNamespace}.CustomEditors");
            using(sb.Block())
            {
                sb.AppendLine($"public static class {rootNamespace.Replace(".", "")}EditorRecords");
                using (sb.Block())
                {
                    sb.AppendLine("extension(global::NodeEditor.Net.Records.CustomEditorRecord record)");
                    using (sb.Block())
                    {
                        foreach (var model in models)
                        {
                            sb.AppendLine($"public static global::NodeEditor.Net.Records.CustomEditorRecord {model.HintTypeName} => new global::NodeEditor.Net.Records.CustomEditorRecord(\"{model.HintTypeName}\");");
                        }
                    }
                }
            }

            context.AddSource($"{rootNamespace.Replace(".", "_")}_CustomNodeEditors.g.cs", sb.ToString());
        }
    }
}
